# Generated by Django 4.0.2 on 2022-02-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_customer_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
